### ISSUE TITLE
VobSub Timestamp Inconsistencies

### ISSUE THREAD

**Issue by timj** [ecdye/macSubtitleOCR#18]
Thank you for making such great progress. I tried a couple more VOBSUB files as promised. Attached are two different failures.

* "crash" is a simple crash. "macSubtitleOCR/VobSubParser.swift:208: Fatal error: Unexpectedly found nil while unwrapping an Optional value"
* "time" is more interesting in that the end timestamps are wrong.

```
18
00:01:12,739 --> 00:08:04,716
I was just a kid, 26 years old.

19
00:01:16,643 --> 00:08:08,620
Anyway...

20
00:01:19,513 --> 00:08:11,490
they were building the lower level
of the George Washington Bridge...
```

It looks like the start timestamps are correct. SubTools does generate correct end timestamps.

[bad.tar.gz](https://github.com/user-attachments/files/17265248/bad.tar.gz)

**Comment by ecdye** [comment]
I figured that would be the case, I knew there was something a little too nice about my tacky timestamp workaround. As for the other issue, I think I have an idea as to what causes the other one, I'll look at it more tomorrow.

**Comment by ecdye** [comment]
OK, I think that I have fixed the timestamp issue now, or at least improved the output. The crash should also be resolved, plus I improved the performance while I was at it to reduce unnecessary seeking around in the file. Let me know if you find anything else.

**Comment by timj** [comment]
Thanks. The "crash" test does pass and the OCR quality is excellent. SubTools/Tesseract is actually unusably bad with those files (almost like the colored text is messing it up).

The timestamps are wrong in that one though. The start times are ine (within a millisecond or so of Subtools) but the end points of some are later than the start of the next so they start piling up when displayed on the video. For example:

```
9
00:02:34,655 --> 00:02:38,195
•..you are violating
our territorial airspace.

10
00:02:37,456 --> 00:02:40,213
What are they talking about?

11
00:02:38,859 --> 00:02:43,191
```

SubTools has these timestamps as:
```
00:02:34.655 --> 00:02:37.249
00:02:37.457 --> 00:02:38.652
00:02:38.859 --> 00:02:41.590
```

**Comment by timj** [comment]
For reference, there is a closed caption subtitle directly in the MKV that exports directly to SRT. That has:

```
00:02:34,554 --> 00:02:37,155
00:02:37,223 --> 00:02:38,590
00:02:38,659 --> 00:02:41,493
```

**Comment by timj** [comment]
I had a quick look for documentation on .sub/.idx files and the situation is dire and most advice is to look at other code to see how they work out the end time.

I think it would be a good start to make sure that the end time of a subtitle is before the start time of the next subtitle and have some maximum duration. That won't be the right answer in many cases but it will stop subtitles piling up on top of each other.

https://github.com/emk/subtitles-rs/blob/master/vobsub/src/sub.rs uses 5 seconds for that. I haven't looked where they work out the end time since they say the 5 seconds is for cases where the end time could not be determined.

**Comment by ecdye** [comment]
I figured it wasn't completely better, hopefully I'll be able to find something at least somewhat consistent. I'll keep working at it, at the very least I can make sure they don't go past the start of the next TS pretty easily.
