### ISSUE TITLE
Could not find codec parameters

### ISSUE THREAD

**Issue by nickinzon** [ecdye/macSubtitleOCR#27]
Hi!

I am trying to get this tool to work. I downloaded the latest Xcode and then built the tool following the steps in the readme. Made macSubtitleOCR executable and added a symlink to /usr/local/bin to add it to the PATH. 

When I execute it with 
> macSubtitleOCR filename.mkv /

it throws these error lines:
> [matroska,webm @ 0x12e804080] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
> Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

Am I missing out on something? I believe, these errors are associated with ffmpeg.

Thanks!

**Comment by ecdye** [comment]
Yes they appear to be, have you tried using the latest nightly build that can be downloaded from the Releases page? It should use the internal decoder by default and might work better. You also might have a file that has a broken subtitle stream, or I just messed up in the FFmpeg code somewhere. I'll investigate a little more tomorrow, but those are some things you might try.

**Comment by nickinzon** [comment]
Thank you for your quick response. I tried again with the latest nightly build and now it works. Thanks a lot!

**Comment by ecdye** [comment]
Great glad to hear it. Let me know if you have any issues with it, I'm happy to help!
