### ISSUE TITLE
Comparing OCR performance

### ISSUE THREAD

**Issue by timj** [ecdye/macSubtitleOCR#29]
Using current `main` and the subtitle track from the fuzz.tgz that I had uploaded previously, I decided to try the four different configurations to see how OCR compared.

For reference the actual text for these two images is:

> Erm, well, we're having a sale on X-Men comics
>
> and I'm drawing Wolverine slashing prices with his adamantine claws.

(which I got by copying and pasting from Preview.app and which is perfect). The ffmpeg images do still have much smaller boundaries than the internal.

## Internal Decoder

```
10
00:00:44,439 --> 00:00:46,571
Erm,well, we'relhaving
fasaleioniX.Menicomics)

11
00:00:47,719 --> 00:00:50,705
and I'mdrawing/Wolverineslashing
prices-with hisiadamantine claws.
```

## Internal + Invert

```
10
00:00:44,439 --> 00:00:46,571
Erm,,well, we'relhaving
(ajsaleioniX.Menicomicsi

11
00:00:47,719 --> 00:00:50,705
and| im drawing/Wolverine.slashing
prices with his adamantine claws.,
```

## ffmpeg decoder

```
10
00:00:44,439 --> 00:00:47,670
Erm, well, we're having
a sale oni X.Men comics

11
00:00:47,719 --> 00:00:52,235
and l'm drawing Wolverine slashing
prices with his:adamantine claws.
```

## ffmpeg + invert

```
10
00:00:44,439 --> 00:00:47,670
Erm, well, we're having
a sale on X-Men comics

11
00:00:47,719 --> 00:00:52,235
andll'im drawing Wolverine slashing
prices with his.adamantine claws.
```

## Summary

For subtitle 10 ffmpeg+invert is perfect but internal has serious issues.
For subtitle 11 ffmpeg gets the first line right and internal+invert is closest for the second line (with an extra comma at the end).

**Comment by timj** [comment]
>  also would love to figure out a way to programmatically add extra spacing between close words in the image but I think that might be a little beyond my ability to do unless I can invent a algorithm to do so, but I'm not holding my breath.

At that point you end up writing your own OCR engine... (or at least you end up writing code that takes the per-letter "fast" mode and then tries to work out how to put those into words better than Apple is managing to do it). Seems like working out what Apple do to get the right answer is a better place to put the work in.

From the Vision docs it says:

> Enabling language correction on the request helps minimize common recognition errors. 

Which really does imply that it would handle the "I'm" case...

**Comment by timj** [comment]
> But IIRC visually the images all look basically the same.

Yes. But wildly different answers...

**Comment by timj** [comment]
Also, the "confidence" values are odd:

```json
      {
        "confidence" : 1,
        "height" : 29,
        "text" : "homelessimale friends?",
        "width" : 347,
        "x" : 1,
        "y" : 7
      }
```
Thinking that's a 1.0 confidence seems wrong. Most of the results are 0.5 or 0.3 confidence. If you ask for more than 1 entry from `topCandidates` how do they compare?

**Comment by ecdye** [comment]
Yeah, I'm running all the possible combinations on my computer right now with fuzz and I'm going to try and do a deep dive into the differences.
I'll compare the 4 you did, plus 2 more being the internal decoder with the old api forced inverted and non.
I'll also do some investigation into the differences between the candidates. I looked at them a little a bit ago, and they seemed to get progressively worse, but I'll investigate some more.

It really does confuse me that they visually can all look so similar to us, but somehow it gives wildly different results from the vision framework.

**Comment by ecdye** [comment]
OK, so I believe I have figured out why it works so well in preview. I think that adding a background to the image seems to drastically improve the performance of the Vision framework when performing OCR. I've just made a change to the code to reflect that. 

I still want to do more research and look into the other ins and outs of these differences, but at least for now, that simple change has made a very big difference in the output, in fact using the default settings now, I only noticed one error, and its a very understandable one that I wouldn't really expect to be caught (for reference it was number 61 in fuzz `well...I` was recognized as `well...l`).  

Let me know if you find any other outliers where the OCR just gives weird output

**Comment by timj** [comment]
Thank you.

1. It's all blindingly fast now. Incredibly impressive work.
2. The OCR is absolutely usable now. Fantastic.

"invert" mode is significantly worse now but it doesn't matter because the default is good. I can try some other examples.

It's still odd that Apple expect you to preprocess the image before passing it to the OCR engine. It seems to defeat the purpose of the clever OCR API if you have to know where the text is and clean up the background but it clearly improved things (and yet Apple can extract the text from images taken from the video images where the subtitles have all sorts of complex background content).

Thanks again.

**Comment by ecdye** [comment]
Of course! 

I suspect it might just have more to do with it not liking the transparent background. I think it may not really care what background is there as long as it's not transparent. I suspect it's because whatever dataset they trained it on didn't have much data for text on a transparent background and it just can't understand it very well sometimes.

**Comment by timj** [comment]
The `l` vs `I` is interesting. I'm pretty sure if I post process the output with `s|\bl\b|I|g` that everything will be essentially perfect.

I've found one crash so far which is entirely justifiable in that after splitting a giant MKV file by chapters with `mkvmerge` the first chapter turns out to be a fraction of a second in length. You end up with a 0-byte sub file and an index file of:

```
# VobSub index file, v7 (do not modify this line!)
# 
# This index block was generated by MakeMKV v1.17.6 darwin(arm64-release)
# which has no relation to VobSub software. The first
# line above is present for compatibility reasons.
# 
size: 720x480
org: 0, 0
alpha: 100%
smooth: OFF
fadein/out: 50, 50
align: OFF at LEFT TOP
time offset: 0
forced subs: OFF
langidx: 0
palette: 0000e1, e83f07, 0f0f0f, d8f74d, 11eb10, ea12eb, faff1a, 095d76, 7c7c7c, e0e0e0, 0cb70b, 91a8d5, d1d1d1, 062ba0, 70e67d, 62c243
# 
# end

id: en, index: 0
```
This crashes everything but maybe it could notice and generate an empty srt file?

(I've also just noticed that the idx file has the two letter language code in it so maybe `--languages` can default to that even for .idx files and not just .mkv)

**Comment by timj** [comment]
Relatedly, this sub file has one timestamp in it and completes without writing anything, but for consistency I'm inclined to think it should write the empty .srt file. I understand that arguments could be made either way.

[empty.tgz](https://github.com/user-attachments/files/17512671/empty.tgz)

**Comment by ecdye** [comment]
Good points, I'll implement that l to I regex in the srt output but not json just for clarity, as I can't see where it would hurt.

I'll also look into making those edge case behaviors more consistent with outputting srt files, and also adding the language hint from the idx file.

**Comment by timj** [comment]
Thanks. Good status but no file works for me -- I can patch my wrapper script. The file that had no idx entries does work now but the original MKV still crashes if you tell it to find the subtitle file inside the MKV.

**Comment by ecdye** [comment]
OK, I thought that might be the case, I'll try to go and fix that.

**Comment by ecdye** [comment]
@timj What error, if any, does it give for the mkv file crash?

**Comment by timj** [comment]
```
macSubtitleOCR/MKVTrackParser.swift:52: Fatal error: Unexpectedly found nil while unwrapping an Optional value
zsh: trace trap  ~/Downloads/macSubtitleOCR/.build/debug/macSubtitleOCR output-001.mkv .
```

**Comment by ecdye** [comment]
OK, I think I fixed that one now, let me know if it works.

**Comment by timj** [comment]
Works great. Thanks.
```
$ macSubtitleOCR output-001.mkv .        
Found empty track data for track 1, skipping track!
Found empty track data for track 2, skipping track!
```
