### ISSUE TITLE
Insufficient RLE data for subtitle.

### ISSUE THREAD

**Issue by nickinzon** [ecdye/macSubtitleOCR#30]
Hi!
I am running into the following error message with one mkv file I am processing:

```
macSubtitleOCR/RLEData.swift:70: Fatal error: Insufficient RLE data for subtitle.
zsh: trace trap  macSubtitleOCR  ./
```

What could be the problem? And what additional information would you need to look into the problem?

Thank you!

**Comment by ecdye** [comment]
Great question! can you show me what command you ran, and then if possible sending me the extracted subtitle file (ie `.sup`) tends to work best so I can debug what exactly would be happening, its possible its a bug in the decoder, or it might just be a badly formed mkv file.

**Comment by nickinzon** [comment]
Hi Ethan,

the command I was using is 
> macSubtitleOCR file.mkv ./ --languages de,en
I just sent you an email regarding the sup files. 

Thank you!

**Comment by ecdye** [comment]
Alright, I think I got it fixed up, there was a minor bug with the PGS decoder and multi-segment ODS packets, which I fixed. Let me know if that fixed it for you

**Comment by nickinzon** [comment]
Thank you, Ethan. I can now process the *.sup files successfully. Though processing an *.mkv file throws an error. Tested with several different *.mkv files.

```
macSubtitleOCR file.mkv ./ --languages de,en
zsh: trace trap  macSubtitleOCR file.mkv ./ --languages de,en
```
