### ISSUE TITLE
End timestamps

### ISSUE THREAD

**Issue by timj** [ecdye/macSubtitleOCR#31]
I've been doing some more tests this weekend and I'm pleased to report that the OCR is essentially perfect. Far better than I've seen from tesseract.

The one remaining issue that I see from a usability perspective is the end timestamps. In fuzz.tgz for example the default encoder gives:

```
9
00:00:42,320 --> 00:00:43,678
Tim, what you doing?

10
00:00:44,439 --> 00:00:46,571
Erm, well, we're having
a sale on X-Men comics

11
00:00:47,719 --> 00:00:50,705
and I'm drawing Wolverine slashing
prices with his adamantine claws.

12
00:00:52,280 --> 00:00:53,970
- I'm also doing a po...
- All right!
```

and the ffmpeg decoder gives:

```
9
00:00:42,320 --> 00:00:44,390
Tim, what you doing?

10
00:00:44,439 --> 00:00:47,670
Erm, well, wete having
a sale en X-Men comies

11
00:00:47,719 --> 00:00:52,235
and I'm drawing Welverine slashing
prices with his adamantine claws.

12
00:00:52,280 --> 00:00:54,919
-Im also doing a po.
- AIl right!
```

The text is much better in the internal decoder but the end timestamp is much better (and synced with what people are saying) in the ffmpeg decoder.

**Comment by ecdye** [comment]
I figured as much, I'm going to have to do some more tweaking to see if I can't figure out how to get those down right. I'm close but still off. Thanks for the feedback, I'll try to look into it.

**Comment by ecdye** [comment]
Alright, I have settled on doing a similar method to subtools and just using default values. In the future I'd like to extend it to be configurable, but for now it seems pretty good.

Interestingly, in my tests it seemed like ffmpeg was giving completely wrong results for timestamps, but I could be doing something different. Let me know if the changes work well for you.

**Comment by timj** [comment]
```macSubtitleOCR/VobSubParser.swift:130: Fatal error: Unexpectedly found nil while unwrapping an Optional value```

on very first thing I tried.

I have no idea why I am getting correct ffmpeg timestamps then. Different version?

**Comment by ecdye** [comment]
Maybe, and yeah I realized something broke and now I'm struggling to figure out a fix, I'll probably get something in later tonight.

**Comment by ecdye** [comment]
OK @timj it should be fixed now, I got rid of the buggy code for now, I can try again on that vein next time.
