### ISSUE TITLE
Processing *.mkv files throws errors

### ISSUE THREAD

**Issue by nickinzon** [ecdye/macSubtitleOCR#33]
Thank you, Ethan. I can now process the *.sup files successfully. Though processing an *.mkv file throws an error. Tested with several different *.mkv files.

```
macSubtitleOCR file.mkv ./ --languages de,en
zsh: trace trap  macSubtitleOCR file.mkv ./ --languages de,en
```

_Originally posted by @nickinzon in https://github.com/ecdye/macSubtitleOCR/issues/30#issuecomment-2443178082_

**Comment by ecdye** [comment]
What kind of subtitle tracks do they contain?

**Comment by nickinzon** [comment]
PGS subtitles.

**Comment by ecdye** [comment]
If possible can you try and compile and run it in a debugger to let me know what the logger output is? If not, its going to be difficult to pinpoint where the issue is without the original files.

**Comment by nickinzon** [comment]
Thank you! That fixed it.
