### ISSUE TITLE
Crash with palette and alpha

### ISSUE THREAD

**Issue by timj** [ecdye/macSubtitleOCR#37]
With a subtitle file that had worked before I am now getting this error:

```
$ macSubtitleOCR crash.sub .
Error: Failed to read image palette and alpha, exiting...
```

[crash.tgz](https://github.com/user-attachments/files/17963478/crash.tgz)

**Comment by ecdye** [comment]
I'll look into it. I might have broken something when I made adjustments for timestamps.

**Comment by ecdye** [comment]
Long shot, but do you know approximately when it was working?

**Comment by timj** [comment]
Breaks with 35a2914eaf86362fe4df6eaf011b05907e3f40c0

**Comment by timj** [comment]
Thanks. Works great now.
